language: haskell
ghc:
  - 7.8
  - 7.6
  - 7.4
matrix:
  allow_failures:
    ghc:
      - 7.8
      - 7.4
install:
  - cabal sandbox init
  - cabal install -j2 --dependencies-only --enable-tests
before_script: cabal configure -ftest
script: cabal run test-pager